kind: pipeline
type: docker
name: imgproxy


steps:
  - name: yarn install
    image: node:10.17
    commands:
      - yarn install

  - name: lint
    image: node:10.17
    commands:
      - npm run lint
