kind: pipeline
type: docker
name: app

steps:
  - name: yarn install
    image: node:10.17
    commands:
      - yarn install

  - name: lint
    image: node:10.17
    commands:
      - yarn lint

  - name: test webhook
    image: alikhil/webhook:1.0
    settings:
      url: https://api.telegram.org/bot1064394215:AAEvwEIHv1QL3jMeLQKSHHJOj-ndKJZE3TQ/sendMessage?chat_id=@drone_demo&text=hello%20world
      method: GET
