kind: pipeline
type: docker
name: imgproxy


steps:
  - name: yarn install
    image: node:8.6
    commands:
      - yarn install

  - name: lint
    image: node:8.6
    commands:
      - npm run lint
